### ISSUE TITLE
Either set `loading` inside apiClient or leave it out completely

### ISSUE THREAD

**Issue by robbevp** [accentor/api-client-js#25]
We currently set a loading prop on each object that is loaded in the indexGenerator, but do not set it for any of the other methods. 
I can see how adding a loaded property makes sense for this package, but then we should set it on all methods.

@chvp do you prefer to set it here or in the web client?

**Comment by chvp** [comment]
This is something for in the web client, IMO. It's not something that every consumer of the API will want to do.
